---
 - name: Change host name Router
   ios_config:
#    lines: hostname {{hostname.name}}
    lines: hostname "{{hostname}}"

 - name: configure ip interfaces
   ios_config:
    lines:
     - "ip address {{ item.0 }}"
     - "description {{ item.1 }}"
    parents: "interface {{ item.2 }}"
   with_together:
     - "{{ipadd}}"
     - "{{desc}}"
     - "{{interface}}"

 - name: up/down interface
   ios_interface:
    name: "{{ item.0 }}"
    enabled: "{{ item.1 }}"
   with_together:
     - "{{interface}}"
     - "{{state}}"