---
#-------------------Lay IP loopback1 ----------------
 - name: Get the Ip loopback1 to the router-ospf-id
   ios_command:
    commands:
     - show ip interface brief | include Loopback 
   register: config
 
# - name: Debug
#   debug: msg="{{ config.stdout[0] | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

#-------------------Cau hinh cac thong so co ban OSPF ----------------
 - name: Config ospf statistic
   ios_command:
    commands:
        - conf t
        - "router ospf {{processID}}"
        - "router-id {{item}}"
   with_items:
    - "{{ config.stdout[0] | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

#-------------------Quang ba dinh tuyen----------------
 - name: Network ospf
   ios_config:
    lines:
        - "ip ospf {{processID}} area {{ item.0 }}"
    parents: "interface {{ item.1 }}"
   with_together:
    - "{{area}}"
    - "{{interface_ospf}}"