---
#-------------------Dat ten --------------------

 hostname: Router03
 
#-------------------Cau hinh IP--------------------

 interface: [ 'FastEthernet0/0', 'FastEthernet1/0', 'FastEthernet2/0', 'loopback 1' ]
 ipadd: [ '192.168.23.3 255.255.255.0', '192.168.3.1 255.255.255.0', '88.0.0.33 255.255.255.0', '3.3.3.3 255.255.255.255' ]
 desc: [ 'From Router3-F0/0 to Router2-F1/0', 'From Router3-F1/0', 'From Router3-F2/0 to Switch', 'loopback1' ]
 state: [ 'True', 'True', 'True', 'True' ]

#-------------------Cau hinh OSPF--------------------
 interface_ospf: [ 'FastEthernet0/0', 'FastEthernet1/0', 'loopback 1' ]
 area: [ '0', '1', '0' ]

#-------------------Cau hinh DHCP--------------------
 ip_exclude: '192.168.3.1 192.168.3.10'
 pool: LAN-POOL-2
 network: 192.168.3.0 255.255.255.0
 default_route: '192.168.3.1'
 interface_dhcp: FastEthernet1/0
